trigger:
- main
pool: MR Agent




steps:
 - task: Bash@3
   inputs:
    filePath: '$(System.DefaultWorkingDirectory)'
    arguments: 'echo "Hello World"'
 - task: TerraformInstaller@0
   inputs:
     terraformVersion: '0.12.3'
 - task: TerraformTaskV2@2
   inputs:
     provider: 'azurerm'
     command: 'init'
     backendServiceArm: 'Azure for Students(0696d9e5-ea22-4caa-be0d-349c87843d62)'
     backendAzureRmResourceGroupName: 'new-rg'
     backendAzureRmStorageAccountName: 'newstorageaccount1230'
     backendAzureRmContainerName: 'newcon'
     backendAzureRmKey: 'main.tfstate'
 
 - task: TerraformTaskV2@2
   inputs:
     provider: 'azurerm'
     command: 'plan'
     environmentServiceNameAzureRM: 'Azure for Students(0696d9e5-ea22-4caa-be0d-349c87843d62)'
 - task: TerraformTaskV2@2
   inputs:
     provider: 'azurerm'
     command: 'apply'
     environmentServiceNameAzureRM: 'Azure for Students(0696d9e5-ea22-4caa-be0d-349c87843d62)'